<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="32941" started-at="2019-01-28T12:22:00Z" finished-at="2019-01-28T12:22:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="32941" started-at="2019-01-28T12:22:00Z" finished-at="2019-01-28T12:22:33Z">
      <class name="extentReportTest.CallingClass_Login">
        <test-method status="PASS" signature="browserSetUp()[pri:0, instance:extentReportTest.CallingClass_Login@7823a2f9]" name="browserSetUp" is-config="true" duration-ms="18582" started-at="2019-01-28T12:22:00Z" finished-at="2019-01-28T12:22:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserSetUp -->
        <test-method status="FAIL" signature="validLoginTest()[pri:0, instance:extentReportTest.CallingClass_Login@7823a2f9]" name="validLoginTest" duration-ms="13505" started-at="2019-01-28T12:22:18Z" finished-at="2019-01-28T12:22:32Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at extentReportTest.CallingClass_Login.validLoginTest(CallingClass_Login.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:extentReportTest.CallingClass_Login@7823a2f9]" name="cleanUp" is-config="true" duration-ms="834" started-at="2019-01-28T12:22:32Z" finished-at="2019-01-28T12:22:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- extentReportTest.CallingClass_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
